### ISSUE TITLE
[Feature Request] Library and poster support

### ISSUE THREAD

**Issue by roormonger** [oonqt/Emby.Notifications.Discord#1]
Hello. I love this plug-in. I was thinking it would be awesome to have an option that changes the "Emby Server" in the notification to the library name it was added to if that is possible. Like instead of it saying "Inception has been added to Emby Server", it would say "Inception has been added to UHD Movies".

Also adding a little poster in the notification would look nice in my opinion.

**Comment by oonqt** [comment]
I will take this into consideration when I eventually go and rework the media added notification, thanks!

**Comment by oonqt** [comment]
Closed. See [https://github.com/oonqt/Emby.Notifications.Discord/releases/tag/1.0.4.2](this release)
