### ISSUE TITLE
Images are not showing in README.md

### ISSUE THREAD

**Issue by salsa2k** [oonqt/Emby.Notifications.Discord#3]
**Describe the bug**
In your documentation, the images are not showing.
https://github.com/oonqt/Emby.Notifications.Discord/blob/master/README.md

**Expected behavior**
See the images example.

**Screenshots**
https://github.com/oonqt/Emby.Notifications.Discord/blob/master/README.md

**Comment by oonqt** [comment]
Image CDN was off for maintenance for a bit, sorry
